# This branch only supports a single version of Gerrit, so no special
# jobs are needed.  But other branches support multiple versions, so
# we define our own job with a distinct name just to avoid confusion.

- job:
    name: plugins-websession-flatfile-build-stable-2.15
    parent: gerrit-plugin-build

- project:
    check:
      jobs:
        - plugins-websession-flatfile-build-stable-2.15
    post:
      jobs:
        - plugins-websession-flatfile-build-stable-2.15
        - gerrit-plugin-publish:
            dependencies:
              - plugins-websession-flatfile-build-stable-2.15
